apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-qa

resources:
  - ../../base
  - namespace.yaml

replicas:
  - name: gitops-nginx
    count: 2

images:
  - name: nginx
    newTag: "fc9119d81705440bc76a93222f041ab7fed918cb"

labels:
  - pairs:
      environment: qa
