apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-qa

resources:
  - ../../base
  - namespace.yaml

replicas:
  - name: gitops-nginx
    count: 2

images:
  - name: nginx
    newTag: "26a905a91b611cd1c8919daaba7a9ce56368a302"

labels:
  - pairs:
      environment: qa
