apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-dev

resources:
  - ../../base
  - namespace.yaml

replicas:
  - name: gitops-nginx
    count: 2

images:
  - name: nginx
    newTag: "1.30"

labels:
  - pairs:
      environment: dev
