apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-dev

resources:
  - ../../base

replicas:
  - name: gitops-nginx
    count: 2

images:
  - name: nginx
    newName: acrgitopslab11068.azurecr.io/aks-demo
    newTag: "fca715780cf95a54b5e4a1d1b9795b96bfdd4193"

labels:
  - pairs:
      environment: dev
    includeSelectors: false
    includeTemplates: true
    include:
      - deployment
      - service
