apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-dev

resources:
  - ../../base

replicas:
  - name: gitops-nginx
    count: 2

images:
  - name: nginx
    newName: acrgitopslab11068.azurecr.io/aks-demo
    newTag: "a945cd82fe08ad0e1f7e16006337cb5733d7e6d9"

labels:
  - pairs:
      environment: dev
    includeSelectors: false
    includeTemplates: true
