name: Promote DEV to QA

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  promote-to-qa:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout DEV
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Read DEV image tag
        id: image
        run: |
          IMAGE_TAG=$(grep 'newTag:' kustomize/gitops-nginx/overlays/dev/kustomization.yaml | sed 's/.*newTag: "\(.*\)"/\1/')

          echo "DEV image tag: $IMAGE_TAG"
          echo "tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Update QA image
        run: |
          sed -i 's|newTag: ".*"|newTag: "${{ steps.image.outputs.tag }}"|' \
            kustomize/gitops-nginx/overlays/qa/kustomization.yaml

      - name: Show QA manifest
        run: |
          cat kustomize/gitops-nginx/overlays/qa/kustomization.yaml

      - name: Create QA promotion PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: promote-to-qa
          base: qa
          title: "Promote ${{ steps.image.outputs.tag }} to QA"
          commit-message: "Promote image ${{ steps.image.outputs.tag }} to QA"
          body: |
            ## QA Promotion

            Promoting the DEV image to QA.

            **Image:**

            `acrgitopslab11068.azurecr.io/aks-demo:${{ steps.image.outputs.tag }}`

            This PR updates the QA GitOps manifest.

            After merge, Argo CD will reconcile the QA environment.
          delete-branch: false
